logo: logo.svg # Путь к файлу с логотипом, относительно .doc-root.yaml
logo_dark: logodark.svg # Путь к файлу с логотипом, относительно .doc-root.yaml в темной теме
title: Тестовая дока # Наименование каталога. Отображается рядом с логотипом
group: products # Группа к которой относится данный каталог (products - доступно всем, projects и company - только сотрудникам компании)
code: MyCode # Код который будет отображаться на плашке в главной странице, только для групп: products, company
style: blue # Стиль, который будет накладываться на код и плашку, только для группы products
order: 1 # Порядок расположения на главной странице. Число может быть нецелым
brand: 0f059d # Цвет, который будет накладываться на плашку, задается только в 16-ой форме и только для группы projects
description: Мое описание. # Описание каталога, которое будет отображаться на плашке в главной странице
description_en: My description. # Описание каталога, которое будет отображаться на плашке в главной странице при переключении языка
lang: ru # Язык по умолчанию
contactEmail: почта@mail.ru # Почтовый ящик, по которому пользователи смогут присылать предложения и замечания к статьям
relatedLinks: # Дополнительные ссылки для отображения на боковой панели
    - url: https://site1
      title: url1
      icon: google-play
      private: true # Ссылка будет скрыта для незарегистрированных пользователей
      iconPrefix: fab # Префикс, который нужен для некоторых иконок посмотреть можно тут: https://fontawesome.com/v5.15/icons?d=gallery&p=2
    - url: https://site2
      title: url2
      icon: gitlab
terms: # Термины
    термин: описание термина
refs: # Внешние ссылки на статьи
    main: path/article # при переходе по ссылке https://docs.ics-it.ru/mdt/ref:main откроется статья https://docs.ics-it.ru/mdt/path/article
